package feishu

import (
	"fmt"
	"strings"

	"github.com/gitlink-org/gitlink-cli/shortcuts/workflow"
)

type Card map[string]interface{}

type WebhookPayload struct {
	Timestamp string            `json:"timestamp,omitempty"`
	Sign      string            `json:"sign,omitempty"`
	MsgType   string            `json:"msg_type"`
	Card      Card              `json:"card,omitempty"`
	Content   map[string]string `json:"content,omitempty"`
}

func NewInteractivePayload(card Card) WebhookPayload {
	return WebhookPayload{
		MsgType: "interactive",
		Card:    card,
	}
}

func BuildBotTestCard(title, message, lang string) Card {
	title = firstNonEmpty(title, "GitLink Feishu integration test")
	message = firstNonEmpty(message, "gitlink-cli can build and send Feishu custom bot cards.")
	return baseCard(title, "blue", []interface{}{
		div("**Status**\nReady"),
		div(message),
		note("Generated by gitlink-cli feishu +bot-test."),
	})
}

func BuildWorkflowCard(report workflow.RepoReportResult, include []string, title string, lang string, docURL string) Card {
	title = firstNonEmpty(title, reportTitle(report, lang))
	elements := []interface{}{
		div(fmt.Sprintf("**Repository**\n%s", escapeMD(report.Repository))),
		fields([]fieldValue{
			{Label: "Report score", Value: fmt.Sprintf("%d", report.ReportScore)},
			{Label: "Risk level", Value: report.RiskLevel},
			{Label: "Source", Value: report.Source},
		}),
	}
	if hasItem(include, "health") {
		healthScore := "N/A"
		healthRisk := "N/A"
		if report.Health != nil {
			healthScore = fmt.Sprintf("%d", report.Health.HealthScore)
			healthRisk = report.Health.RiskLevel
		}
		elements = append(elements, fields([]fieldValue{
			{Label: "Health score", Value: healthScore},
			{Label: "Health risk", Value: healthRisk},
		}))
	}
	if hasItem(include, "issues") {
		elements = append(elements, fields([]fieldValue{
			{Label: "Issues", Value: fmt.Sprintf("%d", report.IssueSummary.Total)},
			{Label: "High risk issues", Value: fmt.Sprintf("%d", report.IssueSummary.HighRisk)},
			{Label: "Missing info", Value: fmt.Sprintf("%d", report.IssueSummary.MissingInfo)},
		}))
	}
	if hasItem(include, "prs") {
		elements = append(elements, fields([]fieldValue{
			{Label: "Pull requests", Value: fmt.Sprintf("%d", report.PRSummary.Total)},
			{Label: "High risk PRs", Value: fmt.Sprintf("%d", report.PRSummary.HighRisk)},
		}))
		if len(report.PRSummary.ReviewFocus) > 0 {
			elements = append(elements, div("**Review focus**\n"+bulletList(report.PRSummary.ReviewFocus, 4)))
		}
	}
	if len(report.Recommendations) > 0 {
		elements = append(elements, div("**Recommendations**\n"+bulletList(report.Recommendations, 5)))
	}
	if strings.TrimSpace(docURL) != "" {
		elements = append(elements, actionButton("Open Feishu report", docURL))
	}
	elements = append(elements, note("Preview is read-only. Bitable records are generated locally by +bitable-records."))
	return baseCard(title, templateForRisk(report.RiskLevel), elements)
}

func reportTitle(report workflow.RepoReportResult, lang string) string {
	if lang == "zh-CN" {
		return "GitLink workflow report: " + report.Repository
	}
	return "GitLink workflow report: " + report.Repository
}

func baseCard(title string, template string, elements []interface{}) Card {
	return Card{
		"config": map[string]interface{}{
			"wide_screen_mode": true,
		},
		"header": map[string]interface{}{
			"template": template,
			"title": map[string]interface{}{
				"tag":     "plain_text",
				"content": title,
			},
		},
		"elements": elements,
	}
}

func div(content string) map[string]interface{} {
	return map[string]interface{}{
		"tag": "div",
		"text": map[string]interface{}{
			"tag":     "lark_md",
			"content": content,
		},
	}
}

type fieldValue struct {
	Label string
	Value string
}

func fields(values []fieldValue) map[string]interface{} {
	result := make([]interface{}, 0, len(values))
	for _, value := range values {
		result = append(result, map[string]interface{}{
			"is_short": true,
			"text": map[string]interface{}{
				"tag":     "lark_md",
				"content": fmt.Sprintf("**%s**\n%s", value.Label, escapeMD(value.Value)),
			},
		})
	}
	return map[string]interface{}{
		"tag":    "div",
		"fields": result,
	}
}

func note(content string) map[string]interface{} {
	return map[string]interface{}{
		"tag": "note",
		"elements": []interface{}{
			map[string]interface{}{
				"tag":     "plain_text",
				"content": content,
			},
		},
	}
}

func actionButton(text string, url string) map[string]interface{} {
	return map[string]interface{}{
		"tag": "action",
		"actions": []interface{}{
			map[string]interface{}{
				"tag": "button",
				"text": map[string]interface{}{
					"tag":     "plain_text",
					"content": text,
				},
				"type": "primary",
				"url":  strings.TrimSpace(url),
			},
		},
	}
}

func bulletList(values []string, limit int) string {
	if limit <= 0 || limit > len(values) {
		limit = len(values)
	}
	lines := make([]string, 0, limit)
	for _, value := range values[:limit] {
		lines = append(lines, "- "+escapeMD(value))
	}
	return strings.Join(lines, "\n")
}

func templateForRisk(risk string) string {
	switch strings.ToLower(strings.TrimSpace(risk)) {
	case "critical":
		return "red"
	case "high":
		return "orange"
	case "medium":
		return "yellow"
	default:
		return "green"
	}
}

func escapeMD(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return "N/A"
	}
	return strings.ReplaceAll(value, "\n", " ")
}
