package feishu

import (
	"fmt"
	"regexp"
	"strings"
)

func isChineseLang(lang string) bool {
	return strings.EqualFold(strings.TrimSpace(lang), "zh-CN")
}

func feishuLabel(lang string, key string) string {
	if !isChineseLang(lang) {
		return feishuLabelsEN[key]
	}
	if value := feishuLabelsZH[key]; value != "" {
		return value
	}
	return feishuLabelsEN[key]
}

func localizeFeishuText(value string, lang string) string {
	value = strings.TrimSpace(value)
	if value == "" || !isChineseLang(lang) {
		return value
	}
	if translated := knownFeishuTranslations[value]; translated != "" {
		return translated
	}
	for _, pattern := range knownFeishuPatterns {
		if match := pattern.re.FindStringSubmatch(value); len(match) > 1 {
			return fmt.Sprintf(pattern.format, match[1])
		}
	}
	return value
}

func localizeFeishuLines(values []string, lang string) []string {
	if !isChineseLang(lang) {
		return values
	}
	result := make([]string, 0, len(values))
	for _, value := range values {
		result = append(result, localizeFeishuText(value, lang))
	}
	return result
}

var feishuLabelsEN = map[string]string{
	"attention":                "Attention",
	"analysis_scope":           "Counts are items analyzed from workflow JSON and may be limited by --issue-limit/--pr-limit; they are not repository totals.",
	"boundary_contributor":     "Contributor digest is role-oriented, not personalized. It does not use Feishu open_id or union_id routing.",
	"boundary_owner":           "Owner digest is a read-only summary. It does not modify GitLink or Feishu resources.",
	"bot_generated":            "Generated by gitlink-cli feishu +bot-test.",
	"bot_message":              "gitlink-cli can build and send Feishu custom bot cards.",
	"bot_status":               "Status",
	"bot_title":                "GitLink Feishu integration test",
	"doc_health":               "Health score: %s; health risk: %s",
	"doc_issues":               "Issues analyzed: %d; high_risk=%d, missing_info=%d",
	"doc_prs":                  "Pull Requests analyzed: %d; high_risk=%d",
	"doc_reasoning":            "Reasoning",
	"doc_recommendations":      "Recommendations",
	"doc_report_score":         "Report score: %d",
	"doc_review_focus":         "Review focus",
	"doc_risk":                 "Risk level: %s",
	"doc_source":               "Source: %s",
	"doc_title":                "GitLink workflow report: %s",
	"health_risk":              "Health risk",
	"health_score":             "Health score",
	"high_risk_issues":         "High-risk issues",
	"high_risk_prs":            "High-risk PRs",
	"issues":                   "Issues",
	"issues_analyzed":          "Issues analyzed",
	"missing_info":             "Missing info",
	"missing_info_issues":      "Missing-info issues",
	"merged_prs":               "Merged PRs",
	"closed_prs":               "Closed/rejected PRs",
	"open_prs":                 "Open PRs",
	"open_feishu_report":       "Open Feishu report",
	"open_gitlink_repository":  "Open GitLink repository",
	"owner_digest_title":       "GitLink owner digest: %s",
	"contributor_digest_title": "GitLink contributor digest: %s",
	"preview_note":             "Preview is read-only. Bitable records are generated locally by +bitable-records.",
	"pull_requests":            "Pull requests",
	"prs_analyzed":             "PRs analyzed",
	"ready":                    "Ready",
	"recommendations":          "Recommendations",
	"report_score":             "Report score",
	"repository":               "Repository",
	"review_focus":             "Review focus",
	"review_audited":           "PRs review-audited",
	"reviewed_prs":             "Reviewed PRs",
	"unreviewed_prs":           "Unreviewed PRs",
	"needs_re_review":          "Needs re-review",
	"formal_reviews":           "Formal reviews",
	"review_actor_attribution": "Review actor attribution",
	"reviewer_comments":        "Reviewer comments",
	"submitter_comments":       "Submitter comments",
	"participant_comments":     "Participant comments",
	"system_events":            "System events",
	"risk_level":               "Risk level",
	"risk_sources":             "PR risk rule sources",
	"source":                   "Source",
	"suggested_next_steps":     "Suggested next steps",
	"task_description_default": "Workflow recommendation from gitlink-cli repo report.",
	"task_missing_info_desc":   "Some issues need reproduction steps, logs, version details, or command output.",
	"task_pr_high_risk_desc":   "High-risk PR bucket from workflow report. Check review focus and merge readiness.",
	"task_review_focus_desc":   "Review focus items from the workflow report.",
	"task_review_report_desc":  "No high-risk task candidates were detected. Keep a regular owner review cadence.",
	"workflow_report_title":    "GitLink workflow report: %s",
}

var feishuLabelsZH = map[string]string{
	"attention":                "需要关注",
	"analysis_scope":           "数量表示 workflow JSON 中实际分析的条目，可能受 --issue-limit/--pr-limit 限制，不代表仓库总量。",
	"boundary_contributor":     "贡献者摘要是按角色生成的汇总，不是基于飞书 open_id 或 union_id 的个人定向推送。",
	"boundary_owner":           "Owner 摘要是只读汇总，不会修改 GitLink 或飞书资源。",
	"bot_generated":            "由 gitlink-cli feishu +bot-test 生成。",
	"bot_message":              "gitlink-cli 可以构建并发送飞书自定义机器人卡片。",
	"bot_status":               "状态",
	"bot_title":                "GitLink 飞书集成测试",
	"doc_health":               "健康分：%s；健康风险：%s",
	"doc_issues":               "已分析 Issue：%d；高风险=%d，信息缺失=%d",
	"doc_prs":                  "已分析 PR：%d；高风险=%d",
	"doc_reasoning":            "判断依据",
	"doc_recommendations":      "建议操作",
	"doc_report_score":         "报告分数：%d",
	"doc_review_focus":         "审查重点",
	"doc_risk":                 "风险等级：%s",
	"doc_source":               "来源：%s",
	"doc_title":                "GitLink 工作流报告：%s",
	"health_risk":              "健康风险",
	"health_score":             "健康分",
	"high_risk_issues":         "高风险 Issue",
	"high_risk_prs":            "高风险 PR",
	"issues":                   "Issue",
	"issues_analyzed":          "已分析 Issue",
	"missing_info":             "信息缺失",
	"missing_info_issues":      "信息缺失 Issue",
	"merged_prs":               "已合并 PR",
	"closed_prs":               "已关闭/拒绝 PR",
	"open_prs":                 "开放 PR",
	"open_feishu_report":       "打开飞书报告",
	"open_gitlink_repository":  "打开 GitLink 仓库",
	"owner_digest_title":       "GitLink Owner 摘要：%s",
	"contributor_digest_title": "GitLink 贡献者摘要：%s",
	"preview_note":             "当前为只读预览。多维表格记录由 +bitable-records 在本地生成。",
	"pull_requests":            "PR",
	"prs_analyzed":             "已分析 PR",
	"ready":                    "就绪",
	"recommendations":          "建议操作",
	"report_score":             "报告分数",
	"repository":               "仓库",
	"review_focus":             "审查重点",
	"review_audited":           "已审查归因 PR",
	"reviewed_prs":             "已被 review 的 PR",
	"unreviewed_prs":           "未被 review 的 PR",
	"needs_re_review":          "待重新 review",
	"formal_reviews":           "正式 Review",
	"review_actor_attribution": "Review 评论来源归因",
	"reviewer_comments":        "Reviewer 评论",
	"submitter_comments":       "提交者评论",
	"participant_comments":     "参与者评论",
	"system_events":            "系统事件",
	"risk_level":               "风险等级",
	"risk_sources":             "PR 风险规则来源",
	"source":                   "来源",
	"suggested_next_steps":     "建议下一步",
	"task_description_default": "来自 gitlink-cli 仓库报告的工作流建议。",
	"task_missing_info_desc":   "部分 Issue 需要补充复现步骤、日志、版本信息或命令输出。",
	"task_pr_high_risk_desc":   "工作流报告识别到高风险 PR，请检查审查重点和合并准备状态。",
	"task_review_focus_desc":   "来自工作流报告的 PR 审查重点。",
	"task_review_report_desc":  "未识别到高风险任务候选，建议保持定期 owner 复查节奏。",
	"workflow_report_title":    "GitLink 工作流报告：%s",
}

var knownFeishuTranslations = map[string]string{
	"Add LICENSE and CONTRIBUTING files for contributor clarity.":                       "补充 LICENSE 和 CONTRIBUTING，降低贡献者理解成本。",
	"Add missing reproduction steps, logs, or screenshots when requested.":              "按需补充复现步骤、日志或截图。",
	"Add or improve README and contribution guidance.":                                  "补充或改进 README 与贡献指南。",
	"Check PR review focus and update the related branch or description.":               "检查 PR 审查重点，并更新相关分支或描述。",
	"Keep GitLink write actions outside this digest; card buttons are navigation-only.": "此摘要不执行 GitLink 写操作；卡片按钮仅用于跳转。",
	"Maintain the current workflow and review the repository report regularly.":         "保持当前维护节奏，并定期复查仓库报告。",
	"No contributor-specific blocker was detected in the workflow report.":              "工作流报告未识别到明确的贡献者阻塞项。",
	"No critical owner action was detected in the workflow report.":                     "工作流报告未识别到紧急 owner 动作。",
	"Open the GitLink repository or Feishu report link for details.":                    "打开 GitLink 仓库或飞书报告查看详情。",
	"Prioritize high or critical risk pull requests.":                                   "优先审阅 high / critical 风险 PR。",
	"Prioritize high-risk pull request feedback before new work.":                       "先处理高风险 PR 反馈，再开始新工作。",
	"Reduce stale issues and add response labels or next actions.":                      "减少长期未处理的 Issue，并补充响应标签或下一步动作。",
	"Request missing information for 3 issues":                                          "为 3 个 Issue 补充缺失信息",
	"Request missing reproduction steps, version, command output, or logs.":             "要求补充复现步骤、版本、命令输出或日志。",
	"Review PR focus areas":                                                "审查 PR 重点区域",
	"Review high-risk issues and PRs first.":                               "优先处理高风险 Issue 和 PR。",
	"Review report risks and schedule the next maintenance actions.":       "复查报告中的风险项，并安排下一步维护动作。",
	"Review stale pull requests and clarify merge blockers.":               "审查长期未处理的 PR，并明确合并阻塞点。",
	"Use the Feishu report document for full context when available.":      "如有飞书报告文档，优先查看完整上下文。",
	"Use the health recommendations to reduce repository governance risk.": "根据健康度建议降低仓库治理风险。",
	"Workflow recommendation from gitlink-cli repo report.":                "来自 gitlink-cli 仓库报告的工作流建议。",
}

var knownFeishuPatterns = []struct {
	re     *regexp.Regexp
	format string
}{
	{regexp.MustCompile(`^(\d+) high-risk issues need maintainer triage$`), "%s 个高风险 Issue 需要维护者分诊"},
	{regexp.MustCompile(`^(\d+) issues are missing required information$`), "%s 个 Issue 缺少必要信息"},
	{regexp.MustCompile(`^(\d+) high-risk pull requests need owner review$`), "%s 个高风险 PR 需要 owner 审阅"},
	{regexp.MustCompile(`^repository health score is (\d+)$`), "仓库健康分为 %s"},
	{regexp.MustCompile(`^(\d+) high-risk pull requests may need contributor updates$`), "%s 个高风险 PR 可能需要贡献者更新"},
	{regexp.MustCompile(`^(\d+) issues need clearer reproduction details or missing information$`), "%s 个 Issue 需要更清晰的复现信息或缺失信息"},
	{regexp.MustCompile(`^(\d+) high-risk issues may need focused follow-up$`), "%s 个高风险 Issue 需要重点跟进"},
	{regexp.MustCompile(`^Request missing information for (\d+) issues$`), "为 %s 个 Issue 补充缺失信息"},
	{regexp.MustCompile(`^Review (\d+) high-risk pull requests$`), "审查 %s 个高风险 PR"},
}
