run:
  timeout: 5m
  go: '1.22'

linters:
  enable:
    - errcheck
    - govet
    - revive
    - unused
    - gosimple
    - ineffassign
    - typecheck

linters-settings:
  revive:
    rules:
      - name: unused-parameter
        severity: warning

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 3
